const genreKeyPath = '';

export const genres = [
  { translateKey: genreKeyPath + 'instrumental-ensembles', value: 'Інструментальні капели. Троїста музика' },
  { translateKey: genreKeyPath + 'polyphonic', value: 'Багатоголосні пісні з сольним виводом' },
  { translateKey: genreKeyPath + 'ballads', value: 'Балади' },
  { translateKey: genreKeyPath + 'kiev-cycle-byliny', value: 'Билини київського циклу' },
  { translateKey: genreKeyPath + 'barge-hauler', value: 'Бурлацькі пісні' },
  { translateKey: genreKeyPath + 'easter-morning-songs', value: 'Великодні ранцівки (волочебні)' },
  { translateKey: genreKeyPath + 'praise', value: 'Величальні колядки та щедрівки' },
  { translateKey: genreKeyPath + 'nativity-scene', value: 'Вертеп (живий, ляльковий)' },
  { translateKey: genreKeyPath + 'spring-songs', value: 'Веснянки' },
  { translateKey: genreKeyPath + 'spring-dances', value: 'Весняні танки та ігри, гаївки' },
  { translateKey: genreKeyPath + 'wedding-ceremony', value: 'Весілля. Недільні обряди і пісні' },
  { translateKey: genreKeyPath + 'bush-walking', value: 'Водіння Куста' },
  { translateKey: genreKeyPath + 'lamentation', value: 'Голосіння' },
  { translateKey: genreKeyPath + 'childrens', value: 'Дитячі колядки та щедрівки' },
  { translateKey: genreKeyPath + 'before-harvest', value: 'До полоття' },
  { translateKey: genreKeyPath + 'wind', value: 'Духові' },
  { translateKey: genreKeyPath + 'humorous', value: 'Жартівливі пісні' },
  { translateKey: genreKeyPath + 'harvest', value: 'Жнивні пісні' },
  { translateKey: genreKeyPath + 'nursery-rhymes', value: 'Забавлянки' },
  { translateKey: genreKeyPath + 'sowing', value: 'Засівання' },
  { translateKey: genreKeyPath + 'welcoming-spring', value: 'Зустріч весни. Заклички' },
  { translateKey: genreKeyPath + 'singing-tales', value: 'Казки зі співом' },
  { translateKey: genreKeyPath + 'porridge', value: 'Каша' },
  { translateKey: genreKeyPath + 'kobzar-artistry', value: 'Кобзарство. Думи' },
  { translateKey: genreKeyPath + 'cossack-historical', value: 'Козацькі пісні, історичні пісні' },
  { translateKey: genreKeyPath + 'lullabies', value: 'Колискові пісні' },
  { translateKey: genreKeyPath + 'spring-summons', value: 'Колодка (Колодій)' },
  { translateKey: genreKeyPath + 'kolomyiky', value: 'Коломийки' },
  { translateKey: genreKeyPath + 'carols', value: 'Колядки, щедрівки' },
  { translateKey: genreKeyPath + 'mower-songs', value: 'Косарські' },
  { translateKey: genreKeyPath + 'spring-rituals', value: 'Креснянка' },
  { translateKey: genreKeyPath + 'kupala', value: 'Купальсько-петрівські пісні' },
  { translateKey: genreKeyPath + 'kychi', value: 'Кічі' },
  { translateKey: genreKeyPath + 'lyre-playing-psalms', value: 'Лірництво. Псальми і канти' },
  { translateKey: genreKeyPath + 'summer-feelings', value: 'Літо' },
  { translateKey: genreKeyPath + 'shrovetide-songs', value: 'Масляні пісні' },
  { translateKey: genreKeyPath + 'hirer', value: 'Наймитські пісні' },
  { translateKey: genreKeyPath + 'influx-dances', value: 'Напливові танці' },
  { translateKey: genreKeyPath + 'birth-christening', value: 'Народини та хрестини' },
  { translateKey: genreKeyPath + 'folk-romances-cruel-romances', value: 'Народні романси. Жорстокі романси' },
  { translateKey: genreKeyPath + 'occasional-choruses', value: 'Оказіональні приспівки до дощу, сонця, птахів' },
  { translateKey: genreKeyPath + 'parody-carols', value: 'Пародійні колядки' },
  { translateKey: genreKeyPath + 'pre-wedding', value: 'Передвесільні обряди і пісні' },
  { translateKey: genreKeyPath + 'ritual-dances', value: 'Питомі танці' },
  { translateKey: genreKeyPath + 'memorial-psalms', value: 'Поминальні псальми' },
  { translateKey: genreKeyPath + 'arrow-funeral', value: 'Похорон Стріли' },
  { translateKey: genreKeyPath + 'dances-choruses', value: 'Приспівки до танців' },
  { translateKey: genreKeyPath + 'love', value: 'Про кохання' },
  { translateKey: genreKeyPath + 'family', value: 'Про родинні відносини' },
  { translateKey: genreKeyPath + 'farewell-to-winter', value: 'Проводи Зими' },
  { translateKey: genreKeyPath + 'psalms', value: 'Псальми' },
  { translateKey: genreKeyPath + 'post-wedding', value: 'Післявесільні звичаї і пісні' },
  { translateKey: genreKeyPath + 'carnival', value: 'Пісні до новорічних карнавальних процесів (Коза, Меланка, Гоготуха, Кінь)' },
  { translateKey: genreKeyPath + 'early', value: 'Ранні ліричні пісні' },
  { translateKey: genreKeyPath + 'recruit-soldier-drayman', value: 'Рекрутські пісні, солдатські пісні, жовнірські пісні' },
  { translateKey: genreKeyPath + 'mermaid-farewell', value: 'Проводи русалок. Русальні пісні' },
  { translateKey: genreKeyPath + 'church-canticles', value: 'Різдвяні канти (церковні колядки)' },
  { translateKey: genreKeyPath + 'christmas-psalms', value: 'Різдвяні псальми' },
  { translateKey: genreKeyPath + 'self-playing', value: 'Самозвучні' },
  { translateKey: genreKeyPath + 'harvest-thanks', value: 'Спасовки' },
  { translateKey: genreKeyPath + 'scything-songs', value: 'Строкові' },
  { translateKey: genreKeyPath + 'string', value: 'Струнні' },
  { translateKey: genreKeyPath + 'shooter-insurgent-songs', value: 'Стрілецькі та повстанські пісні' },
  { translateKey: genreKeyPath + 'percussion', value: 'Ударні' },
  { translateKey: genreKeyPath + 'chants', value: 'Частушки' },
  { translateKey: genreKeyPath + 'chumak', value: 'Чумацькі пісні' },
  { translateKey: genreKeyPath + 'berry-picking', value: 'Ягідні' }
];

export const genresList = [
  'Інструментальні капели. Троїста музика',
  'Багатоголосні пісні з сольним виводом',
  'Балади',
  'Билини київського циклу',
  'Бурлацькі пісні',
  'Великодні ранцівки',
  'Величальні колядки та щедрівки',
  'Вертеп',
  'Веснянки',
  'Весняні танки та ігри',
  'Весілля. Недільні обряди і пісні',
  'Водіння Куста',
  'Голосіння',
  'Дитячі колядки та щедрівки',
  'До полоття',
  'Духові',
  'Жартівливі пісні',
  'Жнивні пісні',
  'Забавлянки',
  'Засівання',
  'Зустріч весни',
  'Казки зі співом',
  'Каша',
  'Кобзарство. Думи',
  'Козацькі пісні, історичні пісні',
  'Колискові пісні',
  'Колодка',
  'Коломийки',
  'Колядки,щедрівки',
  'Косарські',
  'Креснянка',
  'Купальсько-петрівські пісні',
  'Кічі',
  'Лірництво. Псальми і канти',
  'Літо',
  'Масляні пісні',
  'Наймитські пісні',
  'Напливові танці',
  'Народини та хрестини',
  'Народні романси. Жорстокі романси',
  'Оказіональні приспівки до дощу, сонця, птахів',
  'Пародійні колядки',
  'Передвесільні обряди і пісні',
  'Питомі танці',
  'Поминальні псальми',
  'Похорон Стріли',
  'Приспівки до танців',
  'Про кохання',
  'Про родинні відносини',
  'Проводи Зими',
  'Псальми',
  'Післявесільні звичаї і пісні',
  'Пісні до новорічних карнавальних процесів',
  'Ранні ліричні пісні',
  'Рекрутські пісні, солдатські пісні, жовнірські пісні',
  'Русальні пісні',
  'Різдвяні канти',
  'Різдвяні псальми',
  'Самозвучні',
  'Спасовки',
  'Строкові',
  'Струнні',
  'Стрілецькі та повстанські пісні',
  'Ударні',
  'Частушки',
  'Чумацькі пісні',
  'Ягідні'
];
