#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Перевірка, чи знаходимось ми на гілці dev
if [ "$(git rev-parse --abbrev-ref HEAD)" = "dev" ]; then
  dev_branch="dev_branch"
  
  # Перевірка, чи локальна гілка dev оновлена до гілки dev на GitHub
  if [ "$(git rev-parse HEAD)" = "$(git ls-remote origin -h refs/heads/$dev_branch | cut -f1)" ]; then
    echo "Локальна гілка '$dev_branch' оновлена до гілки на GitHub."
  else
    echo "Помилка: Локальна гілка '$dev_branch' не оновлена до гілки '$dev_branch' на GitHub. Спершу оновіть гілку '$dev_branch'"
    exit 1
  fi
fi
