#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Отримати назву головної гілки
dev_branch="dev"
# Отримати назву поточної гілки
current_branch=$(git symbolic-ref --short HEAD)

# Отримати оновлення з віддаленого сховища
git fetch origin $dev_branch

# Перевірити, чи локальна головна гілка оновлена
if git diff --quiet $dev_branch remotes/origin/$dev_branch; then
  echo "Головна гілка $dev_branch оновлена. Можна продовжити пуш."
else
  echo "Головна гілка $dev_branch не оновлена. Будь ласка, оновіть перед пушем."
  exit 1
fi
# Перевірити, чи локальна гілка оновлена з головною гілкою
if git diff --quiet $current_branch pull/origin/$dev_branch; then
  echo "Гілка $current_branch оновлена з головною гілкою $dev_branch. Можна продовжити пуш."
else
  echo "Гілка $current_branch не оновлена з головною гілкою $dev_branch. Будь ласка, оновіть перед пушем."
  git pull origin dev
fi
npm run stylelint
ng test --watch=false --progress=false --browsers=ChromeHeadless