#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Отримати назву головної гілки
dev_branch="dev"
# Отримати назву поточної гілки
current_branch=$(git symbolic-ref --short HEAD)

# Отримати оновлення з віддаленого сховища
git fetch origin $dev_branch

# Перевірити, чи локальна головна гілка оновлена
if git diff --quiet $dev_branch remotes/origin/$dev_branch; then
  echo -e "\e[92mГоловна гілка $dev_branch оновлена. Можна продовжити пуш.\e[0m"
else
  echo -e "\e[91mГоловна гілка $dev_branch не оновлена. Будь ласка, оновіть перед пушем.\e[0m"
  exit 1
fi

npm run stylelint
ng test --watch=false --progress=false --browsers=ChromeHeadless